services:
  app:
    user: "1000:1000"
    build:
      dockerfile: Dockerfile
    volumes:
      - ./data:/data:rw
    environment:
      - STATE_PATH=/data/state.json
    env_file:
      - .env
    restart: unless-stopped
    